---
abstract: 'simple way to turn URIs into QNames'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
keywords:
  - RDF
  - prefixes
  - prefix
  - namespace
  - namespaces
  - xmlns
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Prefixes
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.00
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Prefixes
  homepage: http://search.cpan.org/dist/RDF-Prefixes/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/RDF-Prefixes/
version: 0.001
